projects:
  adminportal:
    schemaPath: src/graphql/schema.json
    includes:
      - todo.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
